### ISSUE TITLE
load magick.js from external server

### ISSUE THREAD

**Issue by cancerberoSgx** [KnicKnic/WASM-ImageMagick#10]
Use cases: 

 * So I'm able to use the library directly importing it from my html page without having to `npm install` or download/copy anything.  i.e `import * as Magick from 'http://some.cdn/magickApi.js'`
 * be able to load the same magick.wasm file from different paths in the same application i.e: /foo/bar/index.html can load /foo/wasm-magick/magick.wasm

(Currently the only way to make it work is if Ii put magick.js and magick.wasm in the same folder as index.html)

**Comment by KnicKnic** [comment]
Attempt to fix this in https://github.com/KnicKnic/WASM-ImageMagick/pull/30

**Comment by KnicKnic** [comment]
with #30 merged, this is just missing documentation and tests for node.
https://knicknic.github.io/wasm-imagemagick/
https://knicknic.github.io/wasm-imagemagick/test1

are example test pages

**Comment by KnicKnic** [comment]
For to close, as fixed in above
