### ISSUE TITLE
RuntimeError: float unrepresentable in integer range

### ISSUE THREAD

**Issue by cancerberoSgx** [KnicKnic/WASM-ImageMagick#12]
Executing commands like the following in small but complex (shaded) images like photos will throw `magick.js:74 exception thrown: RuntimeError: float unrepresentable in integer range,`

```
["convert", "pic.jpg", "-charcoal", "5", "picOut.jpg"]

["convert", "pic.jpg", "-segment", "1x1", "+dither", "-colors", "2", "-edge", "1", "-negate", "-normalize", "picOut.jpg"]
```
Work on simple images, but fails with shaded pictures like photographs (very small ones).

Seems to be a known problem in emscripten that seems to be solved adding a compilation flag: https://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#trap-mode  . I'm investigating what's the case with this project, and I just wanted to track this problem in this issue. Thanks.

**Comment by KnicKnic** [comment]
Can you give an example image. I want to add automated deebug builds and run tests with debug builds first to get stack. I think this failure would help me set that up.

**Comment by cancerberoSgx** [comment]
https://cancerberosgx.github.io/autumn-leaves/rotate.png
https://cancerberosgx.github.io/autumn-leaves/zelda.gif
https://cancerberosgx.github.io/autumn-leaves/holocaust.jpg

**Comment by cancerberoSgx** [comment]
https://github.com/KnicKnic/WASM-ImageMagick/pull/13 solves the problem. 

Unfortunately I still missing jpg and tiff support when building WASM-ImageMagic following the instructions on README using docker exactly. I'm on archlinux using Docker version 18.06.1-ce, build e68fc7a215 . If you could generate a new release after merging this PR I would very appreciate it. In the meanwhile I will research what the problem could be in my system. BTW using docker for this was a great idea, strange that I'm getting different output...

**Comment by cancerberoSgx** [comment]
See it in action here: https://cancerberosgx.github.io/autumn-leaves/#/convertDemo
Somehow I feel now the transformations are faster than before, about double.

**Comment by KnicKnic** [comment]
This built and passed tests, for the binaries see 
https://dev.azure.com/oneeyedelf1/8e3b5d02-1a7d-403f-a745-2767ad9e3a79/_apis/build/builds/40/artifacts?artifactName=magick&api-version=5.0-preview.3&%24format=zip 

Will keep this open until tests are added

**Comment by KnicKnic** [comment]
added test case for this issue in PR https://github.com/KnicKnic/WASM-ImageMagick/pull/14

**Comment by KnicKnic** [comment]
> #13 solves the problem.

Thanks for the FIX!
