### ISSUE TITLE
Abort current operation

### ISSUE THREAD

**Issue by cancerberoSgx** [KnicKnic/WASM-ImageMagick#21]
Is it possible to abort current Call() method call ? Use case: in the browser is common that users perform transformations using visual controls and if input images are large or if the transformation is complex then call() method call could take more than 10 seconds and sometimes even much more. In that cases would be awesome to provide users with the possibility of canceling current call. The only workaround right now is to refresh the page which is undesirable. 

Thanks! any tip is most welcome. Keep it up!

**Comment by KnicKnic** [comment]
You can pass in -limit see 
https://www.imagemagick.org/discourse-server/viewtopic.php?t=19099 is that satisfactory?

**Comment by cancerberoSgx** [comment]
That would solve some problems I'm currently having, didn't knew that one exists. Thanks!, Nevertheless I'm leaving this issue open just in case, but anyway feel free to close it if you feel like so. Thanks!

**Comment by KnicKnic** [comment]
Closing as won't fix and there is an adequate work around.

If someone finds this and this is not an adequate work around or wishes to attempt a PR, please reopen.
