### ISSUE TITLE
changes in libjpeg fork

### ISSUE THREAD

**Issue by cancerberoSgx** [KnicKnic/WASM-ImageMagick#23]
It's important to keep track of the changes you needed to do in IM libraries and this diff is kind of impossible to grasp: 

https://github.com/LuaDist/libjpeg/compare/master...KnicKnic:master 

I wonder if it's just indentation or if there were changes and what are they. 

Reported this issue Just to keep track of this problem. Keep it up

**Comment by KnicKnic** [comment]
I updated their whole library to the latest version. The one on github was an old snapshot, and that is what made that impossible. I seperated that change with the change that was necessary, look at the commit history in the branch. https://github.com/LuaDist/libjpeg/commit/fbaf3bf05b91207ca0a8c96fabc7aa39795b8d78 was the change that got things to work. And it is a complete hack.

**Comment by cancerberoSgx** [comment]
thanks man!
