### ISSUE TITLE
Use Transferable objects to pass data between worker and page

### ISSUE THREAD

**Issue by cancerberoSgx** [KnicKnic/WASM-ImageMagick#33]
It seens that webworkers support transference of data betwee the worker and the page with a zero-copy operation, which results in a vast performance improvement when sending large data sets. We should use that to pass input and output files from and to the web-worker: 

 * https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Passing_data_by_transferring_ownership_(transferable_objects)
 * https://developers.google.com/web/updates/2011/12/Transferable-Objects-Lightning-Fast

**Comment by KnicKnic** [comment]
see call boundries
https://github.com/KnicKnic/WASM-ImageMagick/blob/9226e7cdc39a46424ee1188cc5e9ce77ed81d1d1/src/magickApi.ts#L59-L70

https://github.com/KnicKnic/WASM-ImageMagick/blob/9226e7cdc39a46424ee1188cc5e9ce77ed81d1d1/webworker.js#L92-L96

https://github.com/KnicKnic/WASM-ImageMagick/blob/9226e7cdc39a46424ee1188cc5e9ce77ed81d1d1/webworker.js#L101-L104

https://github.com/KnicKnic/WASM-ImageMagick/blob/9226e7cdc39a46424ee1188cc5e9ce77ed81d1d1/src/magickApi.ts#L139-L150

**Comment by KnicKnic** [comment]
fixed

**Comment by cancerberoSgx** [comment]
Hey @KnicKnic - did it improve performance ? (sorry to be just a spectator lately - promise will resume my work in the short term here since I have a couple of features in my branch and  will need to use the library). Thanks!

**Comment by KnicKnic** [comment]
@cancerberoSgx perf not really(copying a gig of ram doesn't use that much cpu(theoretically the max it could have saved in copying before would have only been .33GB saved twice(coming and going) for a total of .66GB) ). If I remember correctly there were scenarios with many files that it helped reduce the ram usage to such a point where it wouldn't exhaust the 1GB limit in chrome.
