### ISSUE TITLE
build.sh doesn't produce magick.js/.wasm files

### ISSUE THREAD

**Issue by jeffcato** [KnicKnic/WASM-ImageMagick#35]
I attempted to build the latest version per https://github.com/KnicKnic/WASM-ImageMagick#build-instructions.  When the build did not produce the expected **magick.js/.wasm** files, I pulled an older version of the **build.sh**, which produced the files as expected.

The commit I grabbed **build.sh** from: https://github.com/KnicKnic/WASM-ImageMagick/commit/9a7b2ae254dd3be93673c0fec0010a48e8f17f86#diff-0b83f9dedf40d7356e5ca147a077acb4

Edit: added commit reference

**Comment by KnicKnic** [comment]
I am surprised that pipelines is successful then.

**Comment by KnicKnic** [comment]
Pipelines is successfully building magick.js &/.wasm
click on artifacts in https://dev.azure.com/oneeyedelf1/wasm-imagemagick/_build/latest?definitionId=1

**Comment by KnicKnic** [comment]
Apparently in the conversion to typescript the build now requires typescript & npm. This does make it harder on a windows developer, as it has bash constructs and docker doesn't work in wsl. I am not happy about this.

**Comment by KnicKnic** [comment]
updated install instructions in page https://github.com/KnicKnic/WASM-ImageMagick/commit/c7a8573885e5db530ebc73088d5acb1a4359fce8

Windows install instructions are stated broken and using CICD is explained as alternative.

Issue to fix windows install instructions has been created at https://github.com/KnicKnic/WASM-ImageMagick/issues/37
