### ISSUE TITLE
Seems to break on max ram usage

### ISSUE THREAD

**Issue by thibaultmol** [KnicKnic/WASM-ImageMagick#39]
I seem to get issues when the memory on my chromebook reaches max usage during a convert:

Output in console:

```
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 2133196800, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
printErr @ magick.js:32
abort @ magick.js:106
abortOnCannotGrowMemory @ magick.js:106
wasm-function[601]
wasm-function[258]
wasm-function[1162]
wasm-function[792]
wasm-function[277]
wasm-function[1043]
wasm-function[1044]
wasm-function[432]
wasm-function[199]
wasm-function[2068]
(anonymous) @ magick.js:106
invoke_iiiii @ magick.js:106
wasm-function[1511]
wasm-function[2983]
wasm-function[283]
wasm-function[549]
wasm-function[2797]
wasm-function[2791]
wasm-function[1692]
(anonymous) @ magick.js:106
callMain @ magick.js:106
processFiles @ magick.js:69
onmessage @ magick.js:103
magick.js:32 exception thrown: abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 2133196800, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.
printErr @ magick.js:32
callMain @ magick.js:106
processFiles @ magick.js:69
onmessage @ magick.js:103
```

The app itself starts using 2GB or more memory when converting in my case 46 png's that are about 3-4 MB on average

**Comment by KnicKnic** [comment]
are the calls one at a time over and over, or a single call with 46 PNG's?

fixing https://github.com/KnicKnic/WASM-ImageMagick/issues/33 may help with some memory issues, I do know that imagemagick is a bit of a memory hog.

**Comment by thibaultmol** [comment]
Yeah, I dragged all files to it at once

**Comment by KnicKnic** [comment]
What specific link are you using?

**Comment by thibaultmol** [comment]
https://knicknic.github.io/imagemagick/#!%7B%22desc%22%3A%22Site%20lets%20you%20execute%20magick%20commands%20in%20your%20browser%20and%20share%20commands%20via%20url.%22%2C%22cmd%22%3A%22convert%20*%20-resize%20714x231%20-set%20filename%3Amysize%20%25t%20%25%5Bfilename%3Amysize%5D-%25d.jpeg%22%2C%22autoZip%22%3Atrue%2C%22magickEachPicture%22%3Afalse%2C%22showAdvanced%22%3Atrue%7D

**Comment by KnicKnic** [comment]
let me know if you get better results by setting "Run command for each picture"
https://knicknic.github.io/imagemagick/#!%7B"desc"%3A"Site%20lets%20you%20execute%20magick%20commands%20in%20your%20browser%20and%20share%20commands%20via%20url."%2C"cmd"%3A"convert%20*%20-resize%20714x231%20-set%20filename%3Amysize%20%25t%20%25%5Bfilename%3Amysize%5D-%25d.jpeg"%2C"autoZip"%3Atrue%2C"magickEachPicture"%3Atrue%2C"showAdvanced"%3Atrue%7D

Also if you want to tackle the issue https://github.com/KnicKnic/WASM-ImageMagick/issues/33 it may fix things.

**Comment by KnicKnic** [comment]
closing due to run command for each picture fixing it for me.
aslo https://github.com/KnicKnic/WASM-ImageMagick/issues/33 is fixed
