### ISSUE TITLE
output file name in cmdline

### ISSUE THREAD

**Issue by KnicKnic** [KnicKnic/WASM-ImageMagick#5]
I tried to split a filename of abcdefghijklmn.jpg thinking this would generate abcdefghijklmn-0.jpg, abcdefghijklmn-1.jpg, ...
using command `convert * -flatten -crop x20% +repage -quality 100 -scene 0 -set filename:mysize %t %[filename:mysize]-%d.jpeg`

However I got file name abcdefgh0.jpg. This was unexpected for 2 reasons.
1. I did not abcdefghijklmn, but the shortened abcdefgh
My guess is that in the browser it does not detect that it is capable of longer than 8 character file names. I was wondering does anyone know where the detection for what character support your file system has is?
2. I did not get '-'.
How would I get the expected abcdefghijklmn-0.jpg, abcdefghijklmn-1.jpg, ...

Repro steps
[go here](https://knicknic.github.io/imagemagick/#!%7B%22desc%22%3A%22Site%20lets%20you%20execute%20magick%20commands%20in%20your%20browser%20and%20share%20commands%20via%20url.%22%2C%22cmd%22%3A%22convert%20*%20-flatten%20-crop%20x20%25%20%2Brepage%20-quality%20100%20-scene%200%20-set%20filename%3Amysize%20%25t%20%25%5Bfilename%3Amysize%5D-%25d.jpeg%22%2C%22autoZip%22%3Afalse%2C%22magickEachPicture%22%3Afalse%2C%22showAdvanced%22%3Afalse%7D) and upload image named abcdefghijklmn.jpg

**Comment by cancerberoSgx** [comment]
wow this is strange. Out of curiosity, did you compile with windows ? Wonder if the same happen compiling in linux... Strange...

**Comment by KnicKnic** [comment]
I always compile with the emscripten docker container which is Linux. Also now I don't even use my machine to make the release images, just copy from my azure pipelines build ubuntu VM which runs emscripten container.
