### ISSUE TITLE
Execute fails with 'TypeError: Cannot read property 'buffer' of undefined [...]'

### ISSUE THREAD

**Issue by Sidewinder53** [KnicKnic/WASM-ImageMagick#51]
When executing two simple image manipulation commands in a browser environment, the `ExecuteResult` object will contain an error and only the result of the first command is provided.

### Code:
```
import { buildInputFile, execute } from 'https://cdn.jsdelivr.net/npm/wasm-imagemagick/dist/bundles/magickApi.js';

let DoMagickCall = async function () {
  let result = await execute({
    inputFiles: [await buildInputFile('./locked-out.png', 'frame.png')],
    commands: [
      'convert frame.png -rotate 90 image2.png',
      'convert image2.png -rotate 45 image3.png'
    ]
  });

  console.log(result);
}

DoMagickCall();
```

### Result:
```
result:
  errors: Array(2)
    0: undefined
    1: "TypeError: Cannot read property 'buffer' of undefined, exit code: 1, stderr: "
  exitCode: 1
  outputFiles: Array(1)
    0: {name: "image2.png", buffer: Uint8Array(67478)}
  results: Array(2)
    0: {outputFiles: Array(1), stdout: Array(0), stderr: Array(0), exitCode: 0, errors: Array(1)}
    1: {stderr: Array(0), stdout: Array(0), outputFiles: Array(0), exitCode: 1, errors: Array(1)}
```

### Download test files to reproduce
[WASM-ImageMagick_issue_51.zip](https://github.com/KnicKnic/WASM-ImageMagick/files/3389217/WASM-ImageMagick_issue_51.zip)

Any ideas why this is happening? Thanks for your help!

**Comment by cancerberoSgx** [comment]
Just tried and it's working fine for me. I'm on Chrome, which browser are you using ?

**Comment by Sidewinder53** [comment]
Unfortunately, I don't get the same result. Please note that the image appearing in the DOM does not mean that the operation succeeded. You have to open the developer tools and check the first object in the console which will output these errors:

[Google Chrome 75.0.3770.100](https://user-images.githubusercontent.com/19623985/61181256-0423cf80-a624-11e9-9aee-38d317c6bce7.png)

[Microsoft Edge 44.18362.1.0](https://user-images.githubusercontent.com/19623985/61181277-42b98a00-a624-11e9-9253-44b711d04603.png)

[Firefox 69.0b4](https://user-images.githubusercontent.com/19623985/61181283-6977c080-a624-11e9-9f45-01ec29d05484.png)

[Microsoft Edge (Chromium) 77.0.211.3](https://user-images.githubusercontent.com/19623985/61181290-90ce8d80-a624-11e9-81c7-b08ad331c61d.png)

**Comment by cancerberoSgx** [comment]
Solved by https://github.com/KnicKnic/WASM-ImageMagick/commit/5e2351b6d574fc34c435153b92e7c1ee80733570

@KnicKnic this was injected by https://github.com/KnicKnic/WASM-ImageMagick/commit/92f3f7559e3b52fd23e94ed5a0321a0eaac4d4db , if any release or npm publish was made with this commit it will be affected by this issue that basically breaks execute() API, if so, I recommend to generate a new release and publish to npm again

**Comment by charlesj** [comment]
What is the recommended fix for this?  I'm on the latest version 1.2.7, and cannot execute multiple commands in a row at all, regardless of the command.

**Comment by KnicKnic** [comment]
@charlesj currently this bug exists, as you can see there was a purposed bug fix, however this caused a break in other usage of the api.

Someone needs to code a fix that doesn’t cause the regression so both issues are fixed. Either that or if the regression introduced doesn’t bother you, use 1.2.4, which I guess would work for your usecase.

**Comment by KnicKnic** [comment]
fixed in https://github.com/KnicKnic/WASM-ImageMagick/commit/d0213c8fee1a84571e5f93230e2335d9a13ad15f use 1.2.8 for fix
