### ISSUE TITLE
`let` declaration breaks worker

### ISSUE THREAD

**Issue by Axure** [KnicKnic/WASM-ImageMagick#56]
The `onmessage` function provided in the worker file `magick.js` from 'dist` is declared with `let`. Therefore `onmessage` is not a property of `self`, making the script fail to work as expected.

The example given in `README.md` works, because inside their `magick.js`, `onmessage` is introduced without any keyword.

**Comment by KnicKnic** [comment]
fixed in https://github.com/KnicKnic/WASM-ImageMagick/commit/f07635e6866e2b99858fb5c552a7a90e30d785a3

**Comment by KnicKnic** [comment]
@Axure refixed this issue in https://github.com/KnicKnic/WASM-ImageMagick/commit/c84aadbff767d40e2c0c227b1d91d98e88198133 after I got build issues sorted out
