### ISSUE TITLE
Node Support

### ISSUE THREAD

**Issue by TheColorRed** [KnicKnic/WASM-ImageMagick#59]
It would be nice if it was possible to run this in node, but currently it isn't possible as it uses Web Workers which are not a thing in node.

I think the node equivelent would be a [fork](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options)

**Comment by KnicKnic** [comment]
you can make it run against node, it is even in the tests.
see 
https://github.com/KnicKnic/WASM-ImageMagick/blob/d00877f04a4869ac974816b867efff5a6c0373bc/package.json#L23-L24

**Comment by Hypfer** [comment]
But how does one import and use the package from npm in node?

**Comment by jereval0x** [comment]
Is there any way to run this on node?
