### ISSUE TITLE
Fourier transform support

### ISSUE THREAD

**Issue by cancerberoSgx** [KnicKnic/WASM-ImageMagick#7]
Trying to execute the following command: 

```["convert", "rotate.png", "+fft", "+ift", "out.png"]```

throws the following errors: 

```
convert: UnableToOpenConfigureFile `magic.xml' @ warning/configure.c/GetConfigureOptions/714.

magick.js:74 convert: DelegateLibrarySupportNotBuiltIn `rotate.png' (FFTW) @ warning/fourier.c/ForwardFourierTransformImage/898.

magick.js:74 convert: NoImagesDefined `out.png' @ error/convert.c/ConvertImageCommand/3288.
```

I guess for this to work we need to enable some library for these transformations at build time (DelegateLibrarySupportNotBuiltIn).

**Comment by cancerberoSgx** [comment]
Just in case, for FFT to work ImageMagick needs to be compiled / linked with libfft which is currently not. We should document in README which features are not supported like this one and perhaps close this issue. Otherwhise see if it's viable to include that library in the build - and see if adding this feature doesn't have a performance impact (file size). Not closing this issue yet to keep track of this problem

**Comment by KnicKnic** [comment]
It is doc'd what is supported, would like suggestions how to make it clearer. Essentially nothing is supported other than built is + PNG, tiff & jpeg. see https://github.com/KnicKnic/WASM-ImageMagick#status

**Comment by cancerberoSgx** [comment]
Ok, I'm closing this issue - since now it's explicitly documented what's not supported in the README. Thanks
