### ISSUE TITLE
Add Support for JPEG2000 format (.jp2)

### ISSUE THREAD

**Issue by joelviel** [KnicKnic/WASM-ImageMagick#76]
Hi,
I am trying to run:
const command = ["convert", "srcFile.jp2", "out.png"];

I got the following error:
magick.js:32 convert: NoDecodeDelegateForThisImageFormat `JP2' @ error/constitute.c/ReadImage/556.

Is it possible to convert jp2 image to png or jpeg?

**Comment by KnicKnic** [comment]
Currently the code does not include a delegate for JPEG2000. Someone would have to add JPEG2000 to the build and ensure that it is wasm compatile.

**Comment by KnicKnic** [comment]
@joelviel a similar project does have jpeg2000 support, see https://github.com/cancerberoSgx/magica/tree/master/magick-wasm
