### ISSUE TITLE
 Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3000/static/js/magick.js' failed to load.

### ISSUE THREAD

**Issue by greghesp** [KnicKnic/WASM-ImageMagick#79]
I'm using this in a React project and I get an error in the console saying ` Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3000/static/js/magick.js' failed to load.`

**Comment by KnicKnic** [comment]
This is a duplicate issue of https://github.com/KnicKnic/WASM-ImageMagick/issues/78

**Comment by JohnForster** [comment]
@greghesp Did you find a solution for this? I am having the same problem
